export default [
  {
    "name": "Aqua Madoor",
    "art": "rbxgameasset://Images/card-85639257",
    "id": 85639257,
    "type": "Normal Monster",
    "desc": "A wizard of the waters that conjures a liquid wall to crush any enemies that oppose him.",
    "atk": 1200,
    "def": 2000,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "WATER"
  },
  {
    "name": "Armaill",
    "art": "rbxgameasset://Images/card-53153481",
    "id": 53153481,
    "type": "Normal Monster",
    "desc": "A strange warrior who manipulates three deadly blades with both hands and his tail.",
    "atk": 700,
    "def": 1300,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Armed Ninja",
    "art": "rbxgameasset://Images/card-9076207",
    "id": 9076207,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Target 1 Spell Card on the field; destroy that target. (If the target is Set, reveal it, and destroy it if it is a Spell Card. Otherwise, return it to its original position.)",
    "atk": 300,
    "def": 300,
    "level": 1,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Armored Starfish",
    "art": "rbxgameasset://Images/card-17535588",
    "id": 17535588,
    "type": "Normal Monster",
    "desc": "A bluish starfish with a solid hide capable of fending off attacks.",
    "atk": 850,
    "def": 1400,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Basic Insect",
    "art": "rbxgameasset://Images/card-89091579",
    "id": 89091579,
    "type": "Normal Monster",
    "desc": "Usually found traveling in swarms, this creature's ideal environment is the forest.",
    "atk": 500,
    "def": 700,
    "level": 2,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Beast Fangs",
    "art": "rbxgameasset://Images/card-46009906",
    "id": 46009906,
    "type": "Spell Card",
    "desc": "A Beast-Type monster equipped with this card increases its ATK and DEF by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Beaver Warrior",
    "art": "rbxgameasset://Images/card-32452818",
    "id": 32452818,
    "type": "Normal Monster",
    "desc": "What this creature lacks in size it makes up for in defense when battling in the prairie.",
    "atk": 1200,
    "def": 1500,
    "level": 4,
    "race": "Beast-Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Blue-Eyes White Dragon",
    "art": "rbxgameasset://Images/card-89631139",
    "id": 89631139,
    "type": "Normal Monster",
    "desc": "This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.",
    "atk": 3000,
    "def": 2500,
    "level": 8,
    "race": "Dragon",
    "attribute": "LIGHT"
  },
  {
    "name": "Book of Secret Arts",
    "art": "rbxgameasset://Images/card-91595718",
    "id": 91595718,
    "type": "Spell Card",
    "desc": "A Spellcaster-Type monster equipped with this card increases its ATK and DEF by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Celtic Guardian",
    "art": "rbxgameasset://Images/card-91152256",
    "id": 91152256,
    "type": "Normal Monster",
    "desc": "An elf who learned to wield a sword, he baffles enemies with lightning-swift attacks.",
    "atk": 1400,
    "def": 1200,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Charubin the Fire Knight",
    "art": "rbxgameasset://Images/card-37421579",
    "id": 37421579,
    "type": "Fusion Monster",
    "desc": "\"Monster Egg\" + \"Hinotama Soul\"",
    "atk": 1100,
    "def": 800,
    "level": 3,
    "race": "Pyro",
    "attribute": "FIRE"
  },
  {
    "name": "Curse of Dragon",
    "art": "rbxgameasset://Images/card-28279543",
    "id": 28279543,
    "type": "Normal Monster",
    "desc": "A wicked dragon that taps into dark forces to execute a powerful attack.",
    "atk": 2000,
    "def": 1500,
    "level": 5,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Dark Energy",
    "art": "rbxgameasset://Images/card-4614116",
    "id": 4614116,
    "type": "Spell Card",
    "desc": "Increase the ATK and DEF of a Fiend-Type monster equipped with this card by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Dark Gray",
    "art": "rbxgameasset://Images/card-9159938",
    "id": 9159938,
    "type": "Normal Monster",
    "desc": "Entirely gray, this beast has rarely been seen by mortal eyes.",
    "atk": 800,
    "def": 900,
    "level": 3,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Dark Hole",
    "art": "rbxgameasset://Images/card-53129443",
    "id": 53129443,
    "type": "Spell Card",
    "desc": "Destroy all monsters on the field.",
    "race": "Normal"
  },
  {
    "name": "Dark King of the Abyss",
    "art": "rbxgameasset://Images/card-53375573",
    "id": 53375573,
    "type": "Normal Monster",
    "desc": "It's said that this King of the Netherworld once had the power to rule over the dark.",
    "atk": 1200,
    "def": 800,
    "level": 3,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Dark Magician",
    "art": "rbxgameasset://Images/card-36996508",
    "id": 36996508,
    "type": "Normal Monster",
    "desc": "''The ultimate wizard in terms of attack and defense.''",
    "atk": 2500,
    "def": 2100,
    "level": 7,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Darkfire Dragon",
    "art": "rbxgameasset://Images/card-17881964",
    "id": 17881964,
    "type": "Fusion Monster",
    "desc": "\"Firegrass\" + \"Petit Dragon\"",
    "atk": 1500,
    "def": 1250,
    "level": 4,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Darkworld Thorns",
    "art": "rbxgameasset://Images/card-43500484",
    "id": 43500484,
    "type": "Normal Monster",
    "desc": "A thorny plant found in the darklands that wraps itself around any unwary traveler.",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Dissolverock",
    "art": "rbxgameasset://Images/card-40826495",
    "id": 40826495,
    "type": "Normal Monster",
    "desc": "A monster born in the lava pits, it generates intense heat that can melt away its enemies.",
    "atk": 900,
    "def": 1000,
    "level": 3,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Dragon Capture Jar",
    "art": "rbxgameasset://Images/card-50045299",
    "id": 50045299,
    "type": "Trap Card",
    "desc": "Change all face-up Dragon-Type monsters on the field to Defense Position, also they cannot change their battle positions.",
    "race": "Continuous"
  },
  {
    "name": "Dragon Treasure",
    "art": "rbxgameasset://Images/card-1435851",
    "id": 1435851,
    "type": "Spell Card",
    "desc": "A Dragon-Type monster equipped with this card increases its ATK and DEF by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Dragoness the Wicked Knight",
    "art": "rbxgameasset://Images/card-70681994",
    "id": 70681994,
    "type": "Fusion Monster",
    "desc": "\"Armaill\" + \"One-Eyed Shield Dragon\"",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "race": "Warrior",
    "attribute": "WIND"
  },
  {
    "name": "Drooling Lizard",
    "art": "rbxgameasset://Images/card-16353197",
    "id": 16353197,
    "type": "Normal Monster",
    "desc": "A blood-sucking snake in human form that attacks any living being that passes nearby.",
    "atk": 900,
    "def": 800,
    "level": 3,
    "race": "Reptile",
    "attribute": "EARTH"
  },
  {
    "name": "Electro-Whip",
    "art": "rbxgameasset://Images/card-37820550",
    "id": 37820550,
    "type": "Spell Card",
    "desc": "Increase the ATK and DEF of a Thunder-Type monster equipped with this card by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Enchanting Mermaid",
    "art": "rbxgameasset://Images/card-75376965",
    "id": 75376965,
    "type": "Normal Monster",
    "desc": "A beautiful mermaid that lures voyagers to a watery grave.",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Exodia the Forbidden One",
    "art": "rbxgameasset://Images/card-33396948",
    "id": 33396948,
    "type": "Effect Monster",
    "desc": "If you have \"Right Leg of the Forbidden One\", \"Left Leg of the Forbidden One\", \"Right Arm of the Forbidden One\" and \"Left Arm of the Forbidden One\" in addition to this card in your hand, you win the Duel.",
    "atk": 1000,
    "def": 1000,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Fiend Reflection #2",
    "art": "rbxgameasset://Images/card-2863439",
    "id": 2863439,
    "type": "Normal Monster",
    "desc": "A bird-beast that summons reinforcements with a hand mirror.",
    "atk": 1100,
    "def": 1400,
    "level": 4,
    "race": "Winged Beast",
    "attribute": "LIGHT"
  },
  {
    "name": "Final Flame",
    "art": "rbxgameasset://Images/card-73134081",
    "id": 73134081,
    "type": "Spell Card",
    "desc": "Inflict 600 points of damage to your opponent's Life Points.",
    "race": "Normal"
  },
  {
    "name": "Firegrass",
    "art": "rbxgameasset://Images/card-53293545",
    "id": 53293545,
    "type": "Normal Monster",
    "desc": "A fire-breathing plant found growing near volcanoes.",
    "atk": 700,
    "def": 600,
    "level": 2,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Fireyarou",
    "art": "rbxgameasset://Images/card-71407486",
    "id": 71407486,
    "type": "Normal Monster",
    "desc": "A malevolent creature wrapped in flames that attacks enemies with intense fire.",
    "atk": 1300,
    "def": 1000,
    "level": 4,
    "race": "Pyro",
    "attribute": "FIRE"
  },
  {
    "name": "Fissure",
    "art": "rbxgameasset://Images/card-66788016",
    "id": 66788016,
    "type": "Spell Card",
    "desc": "Destroy the 1 face-up monster your opponent controls that has the lowest ATK (your choice, if tied).",
    "race": "Normal"
  },
  {
    "name": "Flame Ghost",
    "art": "rbxgameasset://Images/card-58528964",
    "id": 58528964,
    "type": "Fusion Monster",
    "desc": "\"Skull Servant\" + \"Dissolverock\"",
    "atk": 1000,
    "def": 800,
    "level": 3,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "Flame Manipulator",
    "art": "rbxgameasset://Images/card-34460851",
    "id": 34460851,
    "type": "Normal Monster",
    "desc": "This Spellcaster attacks enemies with fire-related spells such as \"Sea of Flames\" and \"Wall of Fire\".",
    "atk": 900,
    "def": 1000,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "FIRE"
  },
  {
    "name": "Flame Swordsman",
    "art": "rbxgameasset://Images/card-45231177",
    "id": 45231177,
    "type": "Fusion Monster",
    "desc": "\"Flame Manipulator\" + \"Masaki the Legendary Swordsman\"",
    "atk": 1800,
    "def": 1600,
    "level": 5,
    "race": "Warrior",
    "attribute": "FIRE"
  },
  {
    "name": "Flower Wolf",
    "art": "rbxgameasset://Images/card-95952802",
    "id": 95952802,
    "type": "Fusion Monster",
    "desc": "\"Silver Fang\" + \"Darkworld Thorns\"",
    "atk": 1800,
    "def": 1400,
    "level": 5,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Follow Wind",
    "art": "rbxgameasset://Images/card-98252586",
    "id": 98252586,
    "type": "Spell Card",
    "desc": "Increase the ATK and DEF of a Winged Beast-Type monster equipped with this card by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Forest",
    "art": "rbxgameasset://Images/card-87430998",
    "id": 87430998,
    "type": "Spell Card",
    "desc": "All Insect, Beast, Plant, and Beast-Warrior monsters on the field gain 200 ATK/DEF.",
    "race": "Field"
  },
  {
    "name": "Frenzied Panda",
    "art": "rbxgameasset://Images/card-98818516",
    "id": 98818516,
    "type": "Normal Monster",
    "desc": "A savage beast that carries a big bamboo stick for beating down its enemies.",
    "atk": 1200,
    "def": 1000,
    "level": 4,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Fusionist",
    "art": "rbxgameasset://Images/card-1641882",
    "id": 1641882,
    "type": "Fusion Monster",
    "desc": "\"Petit Angel\" + \"Mystical Sheep #2\"",
    "atk": 900,
    "def": 700,
    "level": 3,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Gaia the Dragon Champion",
    "art": "rbxgameasset://Images/card-66889139",
    "id": 66889139,
    "type": "Fusion Monster",
    "desc": "\"Gaia The Fierce Knight\" + \"Curse of Dragon\"",
    "atk": 2600,
    "def": 2100,
    "level": 7,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Gaia The Fierce Knight",
    "art": "rbxgameasset://Images/card-6368038",
    "id": 6368038,
    "type": "Normal Monster",
    "desc": "A knight whose horse travels faster than the wind. His battle-charge is a force to be reckoned with.",
    "atk": 2300,
    "def": 2100,
    "level": 7,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Giant Soldier of Stone",
    "art": "rbxgameasset://Images/card-13039848",
    "id": 13039848,
    "type": "Normal Monster",
    "desc": "A giant warrior made of stone. A punch from this creature has earth-shaking results.",
    "atk": 1300,
    "def": 2000,
    "level": 3,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Goblin's Secret Remedy",
    "art": "rbxgameasset://Images/card-11868825",
    "id": 11868825,
    "type": "Spell Card",
    "desc": "Increase your Life Points by 600 points.",
    "race": "Normal"
  },
  {
    "name": "Gravedigger Ghoul",
    "art": "rbxgameasset://Images/card-82542267",
    "id": 82542267,
    "type": "Spell Card",
    "desc": "Select up to 2 Monster Card(s) from your opponent's Graveyard. Remove the selected card(s) from play.",
    "race": "Normal"
  },
  {
    "name": "Green Phantom King",
    "art": "rbxgameasset://Images/card-22910685",
    "id": 22910685,
    "type": "Normal Monster",
    "desc": "This youthful king of the forests lives in a green world, abundant with trees and wildlife.",
    "atk": 500,
    "def": 1600,
    "level": 3,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Hane-Hane",
    "art": "rbxgameasset://Images/card-7089711",
    "id": 7089711,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Select 1 monster on the field and return it to its owner's hand.",
    "atk": 450,
    "def": 500,
    "level": 2,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Hard Armor",
    "art": "rbxgameasset://Images/card-20060230",
    "id": 20060230,
    "type": "Normal Monster",
    "desc": "A living suit of armor that attacks enemies with a bone-jarring tackle.",
    "atk": 300,
    "def": 1200,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Hinotama",
    "art": "rbxgameasset://Images/card-46130346",
    "id": 46130346,
    "type": "Spell Card",
    "desc": "Inflict 500 damage to your opponent.",
    "race": "Normal"
  },
  {
    "name": "Hinotama Soul",
    "art": "rbxgameasset://Images/card-96851799",
    "id": 96851799,
    "type": "Normal Monster",
    "desc": "An intensely hot flame creature that rams anything standing in its way.",
    "atk": 600,
    "def": 500,
    "level": 2,
    "race": "Pyro",
    "attribute": "FIRE"
  },
  {
    "name": "Hitotsu-Me Giant",
    "art": "rbxgameasset://Images/card-76184692",
    "id": 76184692,
    "type": "Normal Monster",
    "desc": "A one-eyed behemoth with thick, powerful arms made for delivering punishing blows.",
    "atk": 1200,
    "def": 1000,
    "level": 4,
    "race": "Beast-Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Kagemusha of the Blue Flame",
    "art": "rbxgameasset://Images/card-15401633",
    "id": 15401633,
    "type": "Normal Monster",
    "desc": "Serving as a double for the Ruler of the Blue Flame, he's a master swordsman that wields a fine blade.",
    "atk": 800,
    "def": 400,
    "level": 2,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Karbonala Warrior",
    "art": "rbxgameasset://Images/card-54541900",
    "id": 54541900,
    "type": "Fusion Monster",
    "desc": "\"M-Warrior #1\" + \"M-Warrior #2\"",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "King Fog",
    "art": "rbxgameasset://Images/card-84686841",
    "id": 84686841,
    "type": "Normal Monster",
    "desc": "A fiend that dwells in a blinding curtain of smoke.",
    "atk": 1000,
    "def": 900,
    "level": 3,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Kumootoko",
    "art": "rbxgameasset://Images/card-56283725",
    "id": 56283725,
    "type": "Normal Monster",
    "desc": "A massive, intelligent spider that traps enemies with webbing.",
    "atk": 700,
    "def": 1400,
    "level": 3,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Kurama",
    "art": "rbxgameasset://Images/card-85705804",
    "id": 85705804,
    "type": "Normal Monster",
    "desc": "A vicious bird that attacks from the skies with its whip-like tail.",
    "atk": 800,
    "def": 800,
    "level": 3,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Larvas",
    "art": "rbxgameasset://Images/card-94675535",
    "id": 94675535,
    "type": "Normal Monster",
    "desc": "A fast-moving, bird-like creature that strangles opposing monsters with its long, thin arms.",
    "atk": 800,
    "def": 1000,
    "level": 3,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Laser Cannon Armor",
    "art": "rbxgameasset://Images/card-77007920",
    "id": 77007920,
    "type": "Spell Card",
    "desc": "Equip only to an Insect monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Left Arm of the Forbidden One",
    "art": "rbxgameasset://Images/card-7902349",
    "id": 7902349,
    "type": "Normal Monster",
    "desc": "A forbidden left arm sealed by magic. Whosoever breaks this seal will know infinite power.",
    "atk": 200,
    "def": 300,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Left Leg of the Forbidden One",
    "art": "rbxgameasset://Images/card-44519536",
    "id": 44519536,
    "type": "Normal Monster",
    "desc": "A forbidden left leg sealed by magic. Whosoever breaks this seal will know infinite power.",
    "atk": 200,
    "def": 300,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Legendary Sword",
    "art": "rbxgameasset://Images/card-61854111",
    "id": 61854111,
    "type": "Spell Card",
    "desc": "Equip only to a Warrior monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Lesser Dragon",
    "art": "rbxgameasset://Images/card-55444629",
    "id": 55444629,
    "type": "Normal Monster",
    "desc": "A minor dragon incapable of breathing fire.",
    "atk": 1200,
    "def": 1000,
    "level": 4,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "M-Warrior #1",
    "art": "rbxgameasset://Images/card-56342351",
    "id": 56342351,
    "type": "Normal Monster",
    "desc": "Specializing in combination attacks, this warrior uses magnetism to block an enemy's escape.",
    "atk": 1000,
    "def": 500,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "M-Warrior #2",
    "art": "rbxgameasset://Images/card-92731455",
    "id": 92731455,
    "type": "Normal Monster",
    "desc": "Specializing in combination attacks, this warrior is equipped with a tough, magnetically coated armor.",
    "atk": 500,
    "def": 1000,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Machine Conversion Factory",
    "art": "rbxgameasset://Images/card-25769732",
    "id": 25769732,
    "type": "Spell Card",
    "desc": "Equip only to a Machine monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Mammoth Graveyard",
    "art": "rbxgameasset://Images/card-40374923",
    "id": 40374923,
    "type": "Normal Monster",
    "desc": "A mammoth that protects the graves of its pack and is absolutely merciless when facing grave-robbers.",
    "atk": 1200,
    "def": 800,
    "level": 3,
    "race": "Dinosaur",
    "attribute": "EARTH"
  },
  {
    "name": "Man Eater",
    "art": "rbxgameasset://Images/card-93553943",
    "id": 93553943,
    "type": "Normal Monster",
    "desc": "Man-eating plant with poison feelers for attacking enemies.",
    "atk": 800,
    "def": 600,
    "level": 2,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Man-Eater Bug",
    "art": "rbxgameasset://Images/card-54652250",
    "id": 54652250,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Target 1 monster on the field; destroy it.",
    "atk": 450,
    "def": 600,
    "level": 2,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Masaki the Legendary Swordsman",
    "art": "rbxgameasset://Images/card-44287299",
    "id": 44287299,
    "type": "Normal Monster",
    "desc": "Legendary swordmaster Masaki is a veteran of over 100 battles.",
    "atk": 1100,
    "def": 1100,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Meda Bat",
    "art": "rbxgameasset://Images/card-76211194",
    "id": 76211194,
    "type": "Normal Monster",
    "desc": "An eyeball fiend created by a servant of the wicked, it uses \"Dark Blasts\" to blow away its enemies.",
    "atk": 800,
    "def": 400,
    "level": 2,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Metal Dragon",
    "art": "rbxgameasset://Images/card-9293977",
    "id": 9293977,
    "type": "Fusion Monster",
    "desc": "\"Steel Ogre Grotto #1\" + \"Lesser Dragon\"",
    "atk": 1850,
    "def": 1700,
    "level": 6,
    "race": "Machine",
    "attribute": "WIND"
  },
  {
    "name": "Misairuzame",
    "art": "rbxgameasset://Images/card-33178416",
    "id": 33178416,
    "type": "Normal Monster",
    "desc": "A missile-launching fish protected by deadly spikes.",
    "atk": 1400,
    "def": 1600,
    "level": 5,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Monster Egg",
    "art": "rbxgameasset://Images/card-36121917",
    "id": 36121917,
    "type": "Normal Monster",
    "desc": "A warrior hidden within an egg that attacks enemies by flinging eggshells.",
    "atk": 600,
    "def": 900,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Monster Reborn",
    "art": "rbxgameasset://Images/card-83764718",
    "id": 83764718,
    "type": "Spell Card",
    "desc": "Target 1 monster in either GY; Special Summon it.",
    "race": "Normal"
  },
  {
    "name": "Mountain",
    "art": "rbxgameasset://Images/card-50913601",
    "id": 50913601,
    "type": "Spell Card",
    "desc": "All Dragon, Winged Beast, and Thunder monsters on the field gain 200 ATK/DEF.",
    "race": "Field"
  },
  {
    "name": "Mystical Elf",
    "art": "rbxgameasset://Images/card-15025844",
    "id": 15025844,
    "type": "Normal Monster",
    "desc": "A delicate elf that lacks offense, but has a terrific defense backed by mystical power.",
    "atk": 800,
    "def": 2000,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Mystical Moon",
    "art": "rbxgameasset://Images/card-36607978",
    "id": 36607978,
    "type": "Spell Card",
    "desc": "Equip only to a Beast-Warrior-Type monster. It gains 300 ATK and DEF.",
    "race": "Equip"
  },
  {
    "name": "Mystical Sheep #2",
    "art": "rbxgameasset://Images/card-83464209",
    "id": 83464209,
    "type": "Normal Monster",
    "desc": "A monstrous sheep with a long tail for hypnotizing enemies.",
    "atk": 800,
    "def": 1000,
    "level": 3,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Nemuriko",
    "art": "rbxgameasset://Images/card-90963488",
    "id": 90963488,
    "type": "Normal Monster",
    "desc": "A child-like creature that controls a sleep fiend to beckon enemies into eternal slumber.",
    "atk": 800,
    "def": 700,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "One-Eyed Shield Dragon",
    "art": "rbxgameasset://Images/card-33064647",
    "id": 33064647,
    "type": "Normal Monster",
    "desc": "This dragon wears a shield not only for its own protection, but also for ramming its enemies.",
    "atk": 700,
    "def": 1300,
    "level": 3,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Petit Angel",
    "art": "rbxgameasset://Images/card-38142739",
    "id": 38142739,
    "type": "Normal Monster",
    "desc": "A quick-moving and tiny fairy that's very difficult to hit.",
    "atk": 600,
    "def": 900,
    "level": 3,
    "race": "Fairy",
    "attribute": "LIGHT"
  },
  {
    "name": "Petit Dragon",
    "art": "rbxgameasset://Images/card-75356564",
    "id": 75356564,
    "type": "Normal Monster",
    "desc": "A very small dragon known for its vicious attacks.",
    "atk": 600,
    "def": 700,
    "level": 2,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Polymerization",
    "art": "rbxgameasset://Images/card-24094653",
    "id": 24094653,
    "type": "Spell Card",
    "desc": "Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Material.",
    "race": "Normal"
  },
  {
    "name": "Pot of Greed",
    "art": "rbxgameasset://Images/card-55144522",
    "id": 55144522,
    "type": "Spell Card",
    "desc": "Draw 2 cards.",
    "race": "Normal"
  },
  {
    "name": "Power of Kaishin",
    "art": "rbxgameasset://Images/card-77027445",
    "id": 77027445,
    "type": "Spell Card",
    "desc": "Equip only to an Aqua monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Raigeki",
    "art": "rbxgameasset://Images/card-12580477",
    "id": 12580477,
    "type": "Spell Card",
    "desc": "Destroy all monsters your opponent controls.",
    "race": "Normal"
  },
  {
    "name": "Raise Body Heat",
    "art": "rbxgameasset://Images/card-51267887",
    "id": 51267887,
    "type": "Spell Card",
    "desc": "Equip only to a Dinosaur monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Ray & Temperature",
    "art": "rbxgameasset://Images/card-85309439",
    "id": 85309439,
    "type": "Normal Monster",
    "desc": "The Sun and the North Wind join hands to deliver a devastating combination of heat and gale-force winds.",
    "atk": 1000,
    "def": 1000,
    "level": 3,
    "race": "Fairy",
    "attribute": "LIGHT"
  },
  {
    "name": "Reaper of the Cards",
    "art": "rbxgameasset://Images/card-33066139",
    "id": 33066139,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Select 1 Trap Card on the field and destroy it. If the selected card is Set, pick up and see the card. If it is a Trap Card, it is destroyed. If it is a Spell Card, return it to its original position.",
    "atk": 1380,
    "def": 1930,
    "level": 5,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Red Medicine",
    "art": "rbxgameasset://Images/card-38199696",
    "id": 38199696,
    "type": "Spell Card",
    "desc": "Increase your Life Points by 500 points.",
    "race": "Normal"
  },
  {
    "name": "Red-Eyes Black Dragon",
    "art": "rbxgameasset://Images/card-74677422",
    "id": 74677422,
    "type": "Normal Monster",
    "desc": "''A ferocious dragon with a deadly attack.''",
    "atk": 2400,
    "def": 2000,
    "level": 7,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Remove Trap",
    "art": "rbxgameasset://Images/card-51482758",
    "id": 51482758,
    "type": "Spell Card",
    "desc": "Select 1 face-up Trap Card on the field and destroy it.",
    "race": "Normal"
  },
  {
    "name": "Right Arm of the Forbidden One",
    "art": "rbxgameasset://Images/card-70903634",
    "id": 70903634,
    "type": "Normal Monster",
    "desc": "A forbidden right arm sealed by magic. Whosoever breaks this seal will know infinite power.",
    "atk": 200,
    "def": 300,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Right Leg of the Forbidden One",
    "art": "rbxgameasset://Images/card-8124921",
    "id": 8124921,
    "type": "Normal Monster",
    "desc": "A forbidden right leg sealed by magic. Whosoever breaks this seal will know infinite power.",
    "atk": 200,
    "def": 300,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Root Water",
    "art": "rbxgameasset://Images/card-39004808",
    "id": 39004808,
    "type": "Normal Monster",
    "desc": "An amphibian capable of calling up a massive tidal wave from the dark seas to wipe out enemy monsters.",
    "atk": 900,
    "def": 800,
    "level": 3,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Sand Stone",
    "art": "rbxgameasset://Images/card-73051941",
    "id": 73051941,
    "type": "Normal Monster",
    "desc": "Appears from underground and attacks with long, snake-like tentacles.",
    "atk": 1300,
    "def": 1600,
    "level": 5,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Silver Bow and Arrow",
    "art": "rbxgameasset://Images/card-1557499",
    "id": 1557499,
    "type": "Spell Card",
    "desc": "A Fairy-Type monster equipped with this card increases its ATK and DEF by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Silver Fang",
    "art": "rbxgameasset://Images/card-90357090",
    "id": 90357090,
    "type": "Normal Monster",
    "desc": "A snow wolf that's beautiful to the eye, but absolutely vicious in battle.",
    "atk": 1200,
    "def": 800,
    "level": 3,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Skull Red Bird",
    "art": "rbxgameasset://Images/card-10202894",
    "id": 10202894,
    "type": "Normal Monster",
    "desc": "This monster swoops down and attacks with a rain of knives stored in its wings.",
    "atk": 1550,
    "def": 1200,
    "level": 4,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Skull Servant",
    "art": "rbxgameasset://Images/card-32274490",
    "id": 32274490,
    "type": "Normal Monster",
    "desc": "A skeletal ghost that isn't strong but can mean trouble in large numbers.",
    "atk": 300,
    "def": 200,
    "level": 1,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "Sogen",
    "art": "rbxgameasset://Images/card-86318356",
    "id": 86318356,
    "type": "Spell Card",
    "desc": "All Warrior and Beast-Warrior monsters on the field gain 200 ATK/DEF.",
    "race": "Field"
  },
  {
    "name": "Sparks",
    "art": "rbxgameasset://Images/card-76103675",
    "id": 76103675,
    "type": "Spell Card",
    "desc": "Inflict 200 points of damage to your opponent's Life Points.",
    "race": "Normal"
  },
  {
    "name": "Spike Seadra",
    "art": "rbxgameasset://Images/card-85326399",
    "id": 85326399,
    "type": "Normal Monster",
    "desc": "Using the spikes sprouting from its body, this creature stabs its opponents and floods them with electricity.",
    "atk": 1600,
    "def": 1300,
    "level": 5,
    "race": "Sea Serpent",
    "attribute": "WATER"
  },
  {
    "name": "Spirit of the Harp",
    "art": "rbxgameasset://Images/card-80770678",
    "id": 80770678,
    "type": "Normal Monster",
    "desc": "A spirit that soothes the soul with the music of its heavenly harp.",
    "atk": 800,
    "def": 2000,
    "level": 4,
    "race": "Fairy",
    "attribute": "LIGHT"
  },
  {
    "name": "Steel Ogre Grotto #1",
    "art": "rbxgameasset://Images/card-29172562",
    "id": 29172562,
    "type": "Normal Monster",
    "desc": "A steel idol worshipped in the Land of Machines.",
    "atk": 1400,
    "def": 1800,
    "level": 5,
    "race": "Machine",
    "attribute": "EARTH"
  },
  {
    "name": "Stop Defense",
    "art": "rbxgameasset://Images/card-63102017",
    "id": 63102017,
    "type": "Spell Card",
    "desc": "Select 1 Defense Position monster on your opponent's side of the field and change it to Attack Position.",
    "race": "Normal"
  },
  {
    "name": "Succubus Knight",
    "art": "rbxgameasset://Images/card-55291359",
    "id": 55291359,
    "type": "Normal Monster",
    "desc": "A warrior wizard adept in casting bone-chilling spells.",
    "atk": 1650,
    "def": 1300,
    "level": 5,
    "race": "Warrior",
    "attribute": "DARK"
  },
  {
    "name": "Swords of Revealing Light",
    "art": "rbxgameasset://Images/card-72302403",
    "id": 72302403,
    "type": "Spell Card",
    "desc": "After this card's activation, it remains on the field, but you must destroy it during the End Phase of your opponent's 3rd turn. When this card is activated: If your opponent controls a face-down monster, flip all monsters they control face-up. While this card is face-up on the field, your opponent's monsters cannot declare an attack.",
    "race": "Normal"
  },
  {
    "name": "Terra the Terrible",
    "art": "rbxgameasset://Images/card-63308047",
    "id": 63308047,
    "type": "Normal Monster",
    "desc": "Known as a swamp dweller, this creature is a minion of the dark forces.",
    "atk": 1200,
    "def": 1300,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "The 13th Grave",
    "art": "rbxgameasset://Images/card-32864",
    "id": 32864,
    "type": "Normal Monster",
    "desc": "A zombie that suddenly appeared from plot #13 - an empty grave.",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "The Furious Sea King",
    "art": "rbxgameasset://Images/card-18710707",
    "id": 18710707,
    "type": "Normal Monster",
    "desc": "Grand King of the Seven Seas, he's able to summon massive tidal waves to drown the enemy.",
    "atk": 800,
    "def": 700,
    "level": 3,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Trap Hole",
    "art": "rbxgameasset://Images/card-4206964",
    "id": 4206964,
    "type": "Trap Card",
    "desc": "When your opponent Normal or Flip Summons 1 monster with 1000 or more ATK: Target that monster; destroy that target.",
    "race": "Normal"
  },
  {
    "name": "Tri-Horned Dragon",
    "art": "rbxgameasset://Images/card-39111158",
    "id": 39111158,
    "type": "Normal Monster",
    "desc": "An unworthy dragon with three sharp horns sprouting from its head.",
    "atk": 2850,
    "def": 2350,
    "level": 8,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Trial of Nightmare",
    "art": "rbxgameasset://Images/card-77827521",
    "id": 77827521,
    "type": "Normal Monster",
    "desc": "This fiend passes judgment on enemies that are locked in coffins.",
    "atk": 1300,
    "def": 900,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Tripwire Beast",
    "art": "rbxgameasset://Images/card-45042329",
    "id": 45042329,
    "type": "Normal Monster",
    "desc": "This creature attacks with electromagnetic waves.",
    "atk": 1200,
    "def": 1300,
    "level": 4,
    "race": "Thunder",
    "attribute": "EARTH"
  },
  {
    "name": "Turtle Tiger",
    "art": "rbxgameasset://Images/card-37313348",
    "id": 37313348,
    "type": "Normal Monster",
    "desc": "A tiger encased in a protective shell that attacks with razor-sharp fangs.",
    "atk": 1000,
    "def": 1500,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Two-Mouth Darkruler",
    "art": "rbxgameasset://Images/card-57305373",
    "id": 57305373,
    "type": "Normal Monster",
    "desc": "A dinosaur with two deadly jaws, it stores electricity in its horn and releases high voltage bolts from the mouth on its back.",
    "atk": 900,
    "def": 700,
    "level": 3,
    "race": "Dinosaur",
    "attribute": "EARTH"
  },
  {
    "name": "Two-Pronged Attack",
    "art": "rbxgameasset://Images/card-83887306",
    "id": 83887306,
    "type": "Trap Card",
    "desc": "Select and destroy 2 of your monsters and 1 of your opponent's monsters.",
    "race": "Normal"
  },
  {
    "name": "Tyhone",
    "art": "rbxgameasset://Images/card-72842870",
    "id": 72842870,
    "type": "Normal Monster",
    "desc": "Capable of firing cannonballs from its mouth for long-range attacks, this creature is particularly effective in mountain battles.",
    "atk": 1200,
    "def": 1400,
    "level": 4,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Umi",
    "art": "rbxgameasset://Images/card-22702055",
    "id": 22702055,
    "type": "Spell Card",
    "desc": "All Fish, Sea Serpent, Thunder, and Aqua monsters on the field gain 200 ATK/DEF, also all Machine and Pyro monsters on the field lose 200 ATK/DEF.",
    "race": "Field"
  },
  {
    "name": "Uraby",
    "art": "rbxgameasset://Images/card-1784619",
    "id": 1784619,
    "type": "Normal Monster",
    "desc": "Fast on its feet, this dinosaur rips enemies to shreds with its sharp claws.",
    "atk": 1500,
    "def": 800,
    "level": 4,
    "race": "Dinosaur",
    "attribute": "EARTH"
  },
  {
    "name": "Vile Germs",
    "art": "rbxgameasset://Images/card-39774685",
    "id": 39774685,
    "type": "Spell Card",
    "desc": "A Plant-Type monster equipped with this card increases its ATK and DEF by 300 points.",
    "race": "Equip"
  },
  {
    "name": "Violet Crystal",
    "art": "rbxgameasset://Images/card-15052462",
    "id": 15052462,
    "type": "Spell Card",
    "desc": "(This card is not treated as a \"Crystal\" card.)\r\nEquip only to a Zombie monster. It gains 300 ATK/DEF.",
    "race": "Equip"
  },
  {
    "name": "Wasteland",
    "art": "rbxgameasset://Images/card-23424603",
    "id": 23424603,
    "type": "Spell Card",
    "desc": "All Dinosaur, Zombie, and Rock monsters on the field gain 200 ATK/DEF.",
    "race": "Field"
  },
  {
    "name": "Witty Phantom",
    "art": "rbxgameasset://Images/card-36304921",
    "id": 36304921,
    "type": "Normal Monster",
    "desc": "Dressed in a night-black tuxedo, this creature presides over the darkness.",
    "atk": 1400,
    "def": 1300,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Yami",
    "art": "rbxgameasset://Images/card-59197169",
    "id": 59197169,
    "type": "Spell Card",
    "desc": "All Fiend and Spellcaster monsters on the field gain 200 ATK/DEF, also all Fairy monsters on the field lose 200 ATK/DEF.",
    "race": "Field"
  }
];
