export default [
  {
    "name": "7 Colored Fish",
    "art": "rbxgameasset://Images/card-23771716",
    "id": 23771716,
    "type": "Normal Monster",
    "desc": "A rare rainbow fish that has never been caught by mortal man.",
    "atk": 1800,
    "def": 800,
    "level": 4,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Ancient Brain",
    "art": "rbxgameasset://Images/card-42431843",
    "id": 42431843,
    "type": "Normal Monster",
    "desc": "A fallen fairy that is powerful in the dark.",
    "atk": 1000,
    "def": 700,
    "level": 3,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Ancient Elf",
    "art": "rbxgameasset://Images/card-93221206",
    "id": 93221206,
    "type": "Normal Monster",
    "desc": "This elf is rumored to have lived for thousands of years. He leads an army of spirits against his enemies.",
    "atk": 1450,
    "def": 1200,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Ancient Lizard Warrior",
    "art": "rbxgameasset://Images/card-43230671",
    "id": 43230671,
    "type": "Normal Monster",
    "desc": "Before the dawn of man, this lizard warrior ruled supreme.",
    "atk": 1400,
    "def": 1100,
    "level": 4,
    "race": "Reptile",
    "attribute": "EARTH"
  },
  {
    "name": "Armored Lizard",
    "art": "rbxgameasset://Images/card-15480588",
    "id": 15480588,
    "type": "Normal Monster",
    "desc": "A lizard with a very tough hide and a vicious bite.",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "race": "Reptile",
    "attribute": "EARTH"
  },
  {
    "name": "Armored Zombie",
    "art": "rbxgameasset://Images/card-20277860",
    "id": 20277860,
    "type": "Normal Monster",
    "desc": "This warrior blindly swings a deadly blade with devastating force.",
    "atk": 1500,
    "def": 0,
    "level": 3,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "Baby Dragon",
    "art": "rbxgameasset://Images/card-88819587",
    "id": 88819587,
    "type": "Normal Monster",
    "desc": "Much more than just a child, this dragon is gifted with untapped power.",
    "atk": 1200,
    "def": 700,
    "level": 3,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Barrel Dragon",
    "art": "rbxgameasset://Images/card-81480460",
    "id": 81480460,
    "type": "Effect Monster",
    "desc": "Once per turn: You can target 1 monster your opponent controls; toss a coin 3 times and destroy it if at least 2 of the results are heads.",
    "atk": 2600,
    "def": 2200,
    "level": 7,
    "race": "Machine",
    "attribute": "DARK"
  },
  {
    "name": "Battle Steer",
    "art": "rbxgameasset://Images/card-18246479",
    "id": 18246479,
    "type": "Normal Monster",
    "desc": "A bull monster often found in the woods, it charges enemy monsters with a pair of deadly horns.",
    "atk": 1800,
    "def": 1300,
    "level": 5,
    "race": "Beast-Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Bickuribox",
    "art": "rbxgameasset://Images/card-25655502",
    "id": 25655502,
    "type": "Fusion Monster",
    "desc": "\"Crass Clown\" + \"Dream Clown\"",
    "atk": 2300,
    "def": 2000,
    "level": 7,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Big Eye",
    "art": "rbxgameasset://Images/card-16768387",
    "id": 16768387,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Look at up to 5 cards from the top of your Deck, then place them on the top of the Deck in any order.",
    "atk": 1200,
    "def": 1000,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Black Skull Dragon",
    "art": "rbxgameasset://Images/card-11901678",
    "id": 11901678,
    "type": "Fusion Monster",
    "desc": "\"Summoned Skull\" + \"Red-Eyes Black Dragon\"\r\n\r\n\r\n\r\n(This card is always treated as an \"Archfiend\" card.)",
    "atk": 3200,
    "def": 2500,
    "level": 9,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Blackland Fire Dragon",
    "art": "rbxgameasset://Images/card-87564352",
    "id": 87564352,
    "type": "Normal Monster",
    "desc": "A dragon that dwells in the depths of darkness, its vulnerability lies in its poor eyesight.",
    "atk": 1500,
    "def": 800,
    "level": 4,
    "race": "Dragon",
    "attribute": "DARK"
  },
  {
    "name": "Bladefly",
    "art": "rbxgameasset://Images/card-28470714",
    "id": 28470714,
    "type": "Effect Monster",
    "desc": "As long as this card remains face-up on the field, increase the ATK of all WIND monsters by 500 points and decrease the ATK of all EARTH monsters by 400 points.",
    "atk": 600,
    "def": 700,
    "level": 2,
    "race": "Insect",
    "attribute": "WIND"
  },
  {
    "name": "Blast Juggler",
    "art": "rbxgameasset://Images/card-70138455",
    "id": 70138455,
    "type": "Effect Monster",
    "desc": "You can only activate this effect during your Standby Phase. Tribute this face-up card to select and destroy 2 face-up monsters with an ATK 1000 or less.",
    "atk": 800,
    "def": 900,
    "level": 3,
    "race": "Machine",
    "attribute": "FIRE"
  },
  {
    "name": "Block Attack",
    "art": "rbxgameasset://Images/card-25880422",
    "id": 25880422,
    "type": "Spell Card",
    "desc": "Target 1 face-up Attack Position monster your opponent controls; change that target to face-up Defense Position.",
    "race": "Normal"
  },
  {
    "name": "Blue-Winged Crown",
    "art": "rbxgameasset://Images/card-41396436",
    "id": 41396436,
    "type": "Normal Monster",
    "desc": "With hair shaped like a crown and a body encased in bluish white flames, this bird is a formidable sight.",
    "atk": 1600,
    "def": 1200,
    "level": 4,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Bottom Dweller",
    "art": "rbxgameasset://Images/card-81386177",
    "id": 81386177,
    "type": "Normal Monster",
    "desc": "This is one sea creature whose wrath is something monsters fear to face.",
    "atk": 1650,
    "def": 1700,
    "level": 5,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Cannon Soldier",
    "art": "rbxgameasset://Images/card-11384280",
    "id": 11384280,
    "type": "Effect Monster",
    "desc": "You can Tribute 1 monster; inflict 500 damage to your opponent.",
    "atk": 1400,
    "def": 1300,
    "level": 4,
    "race": "Machine",
    "attribute": "DARK"
  },
  {
    "name": "Castle of Dark Illusions",
    "art": "rbxgameasset://Images/card-62121",
    "id": 62121,
    "type": "Flip Effect Monster",
    "desc": "FLIP: All Zombie-Type monsters gain 200 ATK and DEF. During each of your next 4 Standby Phases, each of those Zombie-Type monsters gains 200 more ATK and DEF. These effects last as long as this card is face-up on the field.",
    "atk": 920,
    "def": 1930,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Catapult Turtle",
    "art": "rbxgameasset://Images/card-95727991",
    "id": 95727991,
    "type": "Effect Monster",
    "desc": "Once per turn: You can Tribute 1 monster; inflict damage to your opponent equal to half the Tributed monster's ATK on the field.",
    "atk": 1000,
    "def": 2000,
    "level": 5,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Change of Heart",
    "art": "rbxgameasset://Images/card-4031928",
    "id": 4031928,
    "type": "Spell Card",
    "desc": "Target 1 monster your opponent controls; take control of it until the End Phase.",
    "race": "Normal"
  },
  {
    "name": "Cocoon of Evolution",
    "art": "rbxgameasset://Images/card-40240595",
    "id": 40240595,
    "type": "Effect Monster",
    "desc": "You can target 1 \"Petit Moth\" you control; equip this card from your hand to that target. While equipped by this effect, the original ATK/DEF of that \"Petit Moth\" becomes the ATK/DEF of \"Cocoon of Evolution\".",
    "atk": 0,
    "def": 2000,
    "level": 3,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Crass Clown",
    "art": "rbxgameasset://Images/card-93889755",
    "id": 93889755,
    "type": "Effect Monster",
    "desc": "When this card is changed from Defense Position to Attack Position, return 1 monster on your opponent's side of the field to the owner's hand.",
    "atk": 1350,
    "def": 1400,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Crawling Dragon",
    "art": "rbxgameasset://Images/card-67494157",
    "id": 67494157,
    "type": "Normal Monster",
    "desc": "This weakened dragon can no longer fly, but is still a deadly force to be reckoned with.",
    "atk": 1600,
    "def": 1400,
    "level": 5,
    "race": "Dragon",
    "attribute": "EARTH"
  },
  {
    "name": "Cyber Saurus",
    "art": "rbxgameasset://Images/card-89112729",
    "id": 89112729,
    "type": "Fusion Monster",
    "desc": "\"Blast Juggler\" + \"Two-Headed King Rex\"",
    "atk": 1800,
    "def": 1400,
    "level": 5,
    "race": "Machine",
    "attribute": "EARTH"
  },
  {
    "name": "Dark Elf",
    "art": "rbxgameasset://Images/card-21417692",
    "id": 21417692,
    "type": "Effect Monster",
    "desc": "This card requires a cost of 1000 of your own Life Points to attack.",
    "atk": 2000,
    "def": 800,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Deepsea Shark",
    "art": "rbxgameasset://Images/card-28593363",
    "id": 28593363,
    "type": "Fusion Monster",
    "desc": "\"Bottom Dweller\" + \"Tongyo\"",
    "atk": 1900,
    "def": 1600,
    "level": 5,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Destroyer Golem",
    "art": "rbxgameasset://Images/card-73481154",
    "id": 73481154,
    "type": "Normal Monster",
    "desc": "A golem with a massive right hand for crushing its victims.",
    "atk": 1500,
    "def": 1000,
    "level": 4,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Disk Magician",
    "art": "rbxgameasset://Images/card-76446915",
    "id": 76446915,
    "type": "Normal Monster",
    "desc": "This monster hides in a saucer and only appears when executing an attack.",
    "atk": 1350,
    "def": 1000,
    "level": 4,
    "race": "Machine",
    "attribute": "DARK"
  },
  {
    "name": "Doma The Angel of Silence",
    "art": "rbxgameasset://Images/card-16972957",
    "id": 16972957,
    "type": "Normal Monster",
    "desc": "This fairy rules over the end of existence.",
    "atk": 1600,
    "def": 1400,
    "level": 5,
    "race": "Fairy",
    "attribute": "DARK"
  },
  {
    "name": "Dragon Piper",
    "art": "rbxgameasset://Images/card-55763552",
    "id": 55763552,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Destroy all face-up \"Dragon Capture Jar\"(s) on the field. If you destroy any, change all face-up Dragon-Type monsters on the field to Attack Position.",
    "atk": 200,
    "def": 1800,
    "level": 3,
    "race": "Pyro",
    "attribute": "FIRE"
  },
  {
    "name": "Dream Clown",
    "art": "rbxgameasset://Images/card-13215230",
    "id": 13215230,
    "type": "Effect Monster",
    "desc": "When this card is changed from Attack Position to face-up Defense Position, select 1 monster your opponent controls and destroy it.",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Electric Lizard",
    "art": "rbxgameasset://Images/card-55875323",
    "id": 55875323,
    "type": "Effect Monster",
    "desc": "A non Zombie-Type monster attacking \"Electric Lizard\" cannot attack on its following turn.",
    "atk": 850,
    "def": 800,
    "level": 3,
    "race": "Thunder",
    "attribute": "EARTH"
  },
  {
    "name": "Elegant Egotist",
    "art": "rbxgameasset://Images/card-90219263",
    "id": 90219263,
    "type": "Spell Card",
    "desc": "If \"Harpie Lady\" is on the field: Special Summon 1 \"Harpie Lady\" or \"Harpie Lady Sisters\" from your hand or Deck.",
    "race": "Normal"
  },
  {
    "name": "Empress Judge",
    "art": "rbxgameasset://Images/card-15237615",
    "id": 15237615,
    "type": "Fusion Monster",
    "desc": "\"Queen's Double\" + \"Hibikime\"",
    "atk": 2100,
    "def": 1700,
    "level": 6,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Fake Trap",
    "art": "rbxgameasset://Images/card-3027001",
    "id": 3027001,
    "type": "Trap Card",
    "desc": "Activate only when your opponent activates a Spell, Trap, or Effect Monster's effect that would destroy a Trap Card(s) you control. Destroy this card instead. (If the cards that would have been destroyed are face-down, you can look at them to confirm.)",
    "race": "Normal"
  },
  {
    "name": "Feral Imp",
    "art": "rbxgameasset://Images/card-41392891",
    "id": 41392891,
    "type": "Normal Monster",
    "desc": "A playful little fiend that lurks in the dark, waiting to attack an unwary enemy.",
    "atk": 1300,
    "def": 1400,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Flame Cerebrus",
    "art": "rbxgameasset://Images/card-60862676",
    "id": 60862676,
    "type": "Normal Monster",
    "desc": "Known to many as the \"Burning Executioner\", this monster is capable of burning enemies to cinders.",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "race": "Pyro",
    "attribute": "FIRE"
  },
  {
    "name": "Garnecia Elefantis",
    "art": "rbxgameasset://Images/card-49888191",
    "id": 49888191,
    "type": "Normal Monster",
    "desc": "A monster so heavy that each step rocks the earth.",
    "atk": 2400,
    "def": 2000,
    "level": 7,
    "race": "Beast-Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Gate Guardian",
    "art": "rbxgameasset://Images/card-25833572",
    "id": 25833572,
    "type": "Effect Monster",
    "desc": "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by Tributing 1 \"Sanga of the Thunder\", \"Kazejin\", and \"Suijin\".",
    "atk": 3750,
    "def": 3400,
    "level": 11,
    "race": "Warrior",
    "attribute": "DARK"
  },
  {
    "name": "Gazelle the King of Mythical Beasts",
    "art": "rbxgameasset://Images/card-5818798",
    "id": 5818798,
    "type": "Normal Monster",
    "desc": "This monster moves so fast that it looks like an illusion to mortal eyes.\n\n\n(This card is always treated as a \"Phantom Beast\" card.)",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Germ Infection",
    "art": "rbxgameasset://Images/card-24668830",
    "id": 24668830,
    "type": "Spell Card",
    "desc": "The ATK of a non Machine-Type monster equipped with this card is decreased by 300 points at each of its Standby Phases.",
    "race": "Equip"
  },
  {
    "name": "Giga-Tech Wolf",
    "art": "rbxgameasset://Images/card-8471389",
    "id": 8471389,
    "type": "Normal Monster",
    "desc": "An iron wolf with razor-sharp fangs that can penetrate any armor.",
    "atk": 1200,
    "def": 1400,
    "level": 4,
    "race": "Machine",
    "attribute": "FIRE"
  },
  {
    "name": "Giltia the D. Knight",
    "art": "rbxgameasset://Images/card-51828629",
    "id": 51828629,
    "type": "Fusion Monster",
    "desc": "\"Guardian of the Labyrinth\" + \"Protector of the Throne\"",
    "atk": 1850,
    "def": 1500,
    "level": 5,
    "race": "Warrior",
    "attribute": "LIGHT"
  },
  {
    "name": "Great Moth",
    "art": "rbxgameasset://Images/card-14141448",
    "id": 14141448,
    "type": "Effect Monster",
    "desc": "This monster cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing \"Petit Moth\" during your 4th turn after \"Petit Moth\" has been equipped with \"Cocoon of Evolution\".",
    "atk": 2600,
    "def": 2500,
    "level": 8,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Ground Attacker Bugroth",
    "art": "rbxgameasset://Images/card-58314394",
    "id": 58314394,
    "type": "Normal Monster",
    "desc": "A surface battle robot that was once used for sea warfare.",
    "atk": 1500,
    "def": 1000,
    "level": 4,
    "race": "Machine",
    "attribute": "EARTH"
  },
  {
    "name": "Guardian of the Labyrinth",
    "art": "rbxgameasset://Images/card-89272878",
    "id": 89272878,
    "type": "Normal Monster",
    "desc": "A monster that guards the entrance to the Netherworld.",
    "atk": 1000,
    "def": 1200,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Harpie Lady",
    "art": "rbxgameasset://Images/card-76812113",
    "id": 76812113,
    "type": "Normal Monster",
    "desc": "This human-shaped animal with wings is beautiful to watch but deadly in battle.",
    "atk": 1300,
    "def": 1400,
    "level": 4,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Harpie Lady Sisters",
    "art": "rbxgameasset://Images/card-12206212",
    "id": 12206212,
    "type": "Effect Monster",
    "desc": "Cannot be Normal Summoned/Set. Must first be Special Summoned with \"Elegant Egotist\".",
    "atk": 1950,
    "def": 2100,
    "level": 6,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Heavy Storm",
    "art": "rbxgameasset://Images/card-19613556",
    "id": 19613556,
    "type": "Spell Card",
    "desc": "Destroy all Spell and Trap Cards on the field.",
    "race": "Normal"
  },
  {
    "name": "Hibikime",
    "art": "rbxgameasset://Images/card-64501875",
    "id": 64501875,
    "type": "Normal Monster",
    "desc": "Confuses enemy monsters with a noise that is harsh to the ears.",
    "atk": 1450,
    "def": 1000,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Horn of Heaven",
    "art": "rbxgameasset://Images/card-98069388",
    "id": 98069388,
    "type": "Trap Card",
    "desc": "When a monster(s) would be Summoned: Tribute 1 monster; negate the Summon, and if you do, destroy that monster(s).",
    "race": "Counter"
  },
  {
    "name": "Hoshiningen",
    "art": "rbxgameasset://Images/card-67629977",
    "id": 67629977,
    "type": "Effect Monster",
    "desc": "All LIGHT monsters on the field gain 500 ATK, also all DARK monsters on the field lose 400 ATK.",
    "atk": 500,
    "def": 700,
    "level": 2,
    "race": "Fairy",
    "attribute": "LIGHT"
  },
  {
    "name": "Hunter Spider",
    "art": "rbxgameasset://Images/card-80141480",
    "id": 80141480,
    "type": "Normal Monster",
    "desc": "This monster feeds on whatever it catches in its web.",
    "atk": 1600,
    "def": 1400,
    "level": 5,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Hyosube",
    "art": "rbxgameasset://Images/card-2118022",
    "id": 2118022,
    "type": "Normal Monster",
    "desc": "This amphibian is strong on the attack, but leaves much to be desired when defending.",
    "atk": 1500,
    "def": 900,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Illusionist Faceless Mage",
    "art": "rbxgameasset://Images/card-28546905",
    "id": 28546905,
    "type": "Normal Monster",
    "desc": "Manipulates enemy attacks with the power of illusion.",
    "atk": 1200,
    "def": 2200,
    "level": 5,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Insect Soldiers of the Sky",
    "art": "rbxgameasset://Images/card-7019529",
    "id": 7019529,
    "type": "Effect Monster",
    "desc": "If this card attacks a WIND monster, it gains 1000 ATK during the Damage Step only.",
    "atk": 1000,
    "def": 800,
    "level": 3,
    "race": "Insect",
    "attribute": "WIND"
  },
  {
    "name": "Jellyfish",
    "art": "rbxgameasset://Images/card-14851496",
    "id": 14851496,
    "type": "Normal Monster",
    "desc": "An almost invisible, semi-transparent jellyfish that drifts in the sea.",
    "atk": 1200,
    "def": 1500,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Jinzo #7",
    "art": "rbxgameasset://Images/card-32809211",
    "id": 32809211,
    "type": "Effect Monster",
    "desc": "This monster can attack your opponent's Life Points directly.",
    "atk": 500,
    "def": 400,
    "level": 2,
    "race": "Machine",
    "attribute": "DARK"
  },
  {
    "name": "Jirai Gumo",
    "art": "rbxgameasset://Images/card-94773007",
    "id": 94773007,
    "type": "Effect Monster",
    "desc": "When this card declares an attack: Toss a coin and call it. If you call it wrong, lose half your Life Points.",
    "atk": 2200,
    "def": 100,
    "level": 4,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Kaminari Attack",
    "art": "rbxgameasset://Images/card-9653271",
    "id": 9653271,
    "type": "Fusion Monster",
    "desc": "\"Ocubeam\" + \"Mega Thunderball\"",
    "atk": 1900,
    "def": 1400,
    "level": 5,
    "race": "Thunder",
    "attribute": "WIND"
  },
  {
    "name": "Kazejin",
    "art": "rbxgameasset://Images/card-62340868",
    "id": 62340868,
    "type": "Effect Monster",
    "desc": "During damage calculation in your opponent's turn, if this card is being attacked: You can target the attacking monster; make that target's ATK 0 during damage calculation only (this is a Quick Effect). This effect can only be used once while this card is face-up on the field.",
    "atk": 2400,
    "def": 2200,
    "level": 7,
    "race": "Spellcaster",
    "attribute": "WIND"
  },
  {
    "name": "Killer Needle",
    "art": "rbxgameasset://Images/card-88979991",
    "id": 88979991,
    "type": "Normal Monster",
    "desc": "A huge bee with exceptional strength that's particularly dangerous in a swarm.",
    "atk": 1200,
    "def": 1000,
    "level": 4,
    "race": "Insect",
    "attribute": "WIND"
  },
  {
    "name": "King of Yamimakai",
    "art": "rbxgameasset://Images/card-69455834",
    "id": 69455834,
    "type": "Normal Monster",
    "desc": "Wields the power of darkness to destroy its enemies.",
    "atk": 2000,
    "def": 1530,
    "level": 5,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Kojikocy",
    "art": "rbxgameasset://Images/card-1184620",
    "id": 1184620,
    "type": "Normal Monster",
    "desc": "A man-hunter with powerful arms that can crush boulders.",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Kuriboh",
    "art": "rbxgameasset://Images/card-40640057",
    "id": 40640057,
    "type": "Effect Monster",
    "desc": "During damage calculation, if your opponent's monster attacks (Quick Effect): You can discard this card; you take no battle damage from that battle.",
    "atk": 300,
    "def": 200,
    "level": 1,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Labyrinth Tank",
    "art": "rbxgameasset://Images/card-99551425",
    "id": 99551425,
    "type": "Fusion Monster",
    "desc": "\"Giga-Tech Wolf\" + \"Cannon Soldier\"",
    "atk": 2400,
    "def": 2400,
    "level": 7,
    "race": "Machine",
    "attribute": "DARK"
  },
  {
    "name": "Lady of Faith",
    "art": "rbxgameasset://Images/card-17358176",
    "id": 17358176,
    "type": "Normal Monster",
    "desc": "Soothes the souls of others by chanting a mysterious spell.",
    "atk": 1100,
    "def": 800,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Larvae Moth",
    "art": "rbxgameasset://Images/card-87756343",
    "id": 87756343,
    "type": "Effect Monster",
    "desc": "This monster cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing \"Petit Moth\" during your 2nd turn after \"Petit Moth\" has been equipped with \"Cocoon of Evolution\".",
    "atk": 500,
    "def": 400,
    "level": 2,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Launcher Spider",
    "art": "rbxgameasset://Images/card-87322377",
    "id": 87322377,
    "type": "Normal Monster",
    "desc": "A mechanical spider with rocket launchers capable of random fire.",
    "atk": 2200,
    "def": 2500,
    "level": 7,
    "race": "Machine",
    "attribute": "FIRE"
  },
  {
    "name": "Lava Battleguard",
    "art": "rbxgameasset://Images/card-20394040",
    "id": 20394040,
    "type": "Effect Monster",
    "desc": "This card gains 500 ATK for each \"Swamp Battleguard\" you control.",
    "atk": 1550,
    "def": 1800,
    "level": 5,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Leghul",
    "art": "rbxgameasset://Images/card-12472242",
    "id": 12472242,
    "type": "Effect Monster",
    "desc": "This monster may attack your opponent's Life Points directly.",
    "atk": 300,
    "def": 350,
    "level": 1,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Leogun",
    "art": "rbxgameasset://Images/card-10538007",
    "id": 10538007,
    "type": "Normal Monster",
    "desc": "Huge monster with a lion's mane similar to the King of Beasts.",
    "atk": 1750,
    "def": 1550,
    "level": 5,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Little Chimera",
    "art": "rbxgameasset://Images/card-68658728",
    "id": 68658728,
    "type": "Effect Monster",
    "desc": "All FIRE monsters on the field gain 500 ATK. All WATER monsters on the field lose 400 ATK.",
    "atk": 600,
    "def": 550,
    "level": 2,
    "race": "Beast",
    "attribute": "FIRE"
  },
  {
    "name": "Magic Jammer",
    "art": "rbxgameasset://Images/card-77414722",
    "id": 77414722,
    "type": "Trap Card",
    "desc": "When a Spell Card is activated: Discard 1 card; negate the activation, and if you do, destroy it.",
    "race": "Counter"
  },
  {
    "name": "Magician of Faith",
    "art": "rbxgameasset://Images/card-31560081",
    "id": 31560081,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Target 1 Spell in your GY; add that target to your hand.",
    "atk": 300,
    "def": 400,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Mask of Darkness",
    "art": "rbxgameasset://Images/card-28933734",
    "id": 28933734,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Target 1 Trap in your GY; add that target to your hand.",
    "atk": 900,
    "def": 400,
    "level": 2,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Masked Sorcerer",
    "art": "rbxgameasset://Images/card-10189126",
    "id": 10189126,
    "type": "Effect Monster",
    "desc": "When this card inflicts Battle Damage to your opponent's Life Points, draw 1 card from your Deck.",
    "atk": 900,
    "def": 1400,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Mega Thunderball",
    "art": "rbxgameasset://Images/card-21817254",
    "id": 21817254,
    "type": "Normal Monster",
    "desc": "Rolls along the ground releasing bolts of electricity to attack its enemies.",
    "atk": 750,
    "def": 600,
    "level": 2,
    "race": "Thunder",
    "attribute": "WIND"
  },
  {
    "name": "Milus Radiant",
    "art": "rbxgameasset://Images/card-7489323",
    "id": 7489323,
    "type": "Effect Monster",
    "desc": "As long as this card remains face-up on the field, increase the ATK of all EARTH monsters by 500 points and decrease the ATK of all WIND monsters by 400 points.",
    "atk": 300,
    "def": 250,
    "level": 1,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Mirror Force",
    "art": "rbxgameasset://Images/card-44095762",
    "id": 44095762,
    "type": "Trap Card",
    "desc": "When an opponent's monster declares an attack: Destroy all your opponent's Attack Position monsters.",
    "race": "Normal"
  },
  {
    "name": "Morinphen",
    "art": "rbxgameasset://Images/card-55784832",
    "id": 55784832,
    "type": "Normal Monster",
    "desc": "A strange fiend with long arms and razor-sharp talons.",
    "atk": 1550,
    "def": 1300,
    "level": 5,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Muka Muka",
    "art": "rbxgameasset://Images/card-46657337",
    "id": 46657337,
    "type": "Effect Monster",
    "desc": "This card gains 300 ATK and DEF for each card in your hand.",
    "atk": 600,
    "def": 300,
    "level": 2,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Mushroom Man #2",
    "art": "rbxgameasset://Images/card-93900406",
    "id": 93900406,
    "type": "Effect Monster",
    "desc": "A player controlling this monster loses 300 Life Points during each of his/her Standby Phases when this card is face-up on the field. Control of this card is shifted to your opponent by paying 500 Life Points at your own End Phase.",
    "atk": 1250,
    "def": 800,
    "level": 3,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Musician King",
    "art": "rbxgameasset://Images/card-56907389",
    "id": 56907389,
    "type": "Fusion Monster",
    "desc": "\"Witch of the Black Forest\" + \"Lady of Faith\"",
    "atk": 1750,
    "def": 1500,
    "level": 5,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Mystic Horseman",
    "art": "rbxgameasset://Images/card-68516705",
    "id": 68516705,
    "type": "Normal Monster",
    "desc": "Half man and half horse, this monster is known for its extreme speed.",
    "atk": 1300,
    "def": 1550,
    "level": 4,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Mystic Lamp",
    "art": "rbxgameasset://Images/card-98049915",
    "id": 98049915,
    "type": "Effect Monster",
    "desc": "This monster can attack your opponent's Life Points directly.",
    "atk": 400,
    "def": 300,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Niwatori",
    "art": "rbxgameasset://Images/card-7805359",
    "id": 7805359,
    "type": "Normal Monster",
    "desc": "Swallows enemies whole and uses their essence as energy.",
    "atk": 900,
    "def": 800,
    "level": 3,
    "race": "Winged Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Ocubeam",
    "art": "rbxgameasset://Images/card-86088138",
    "id": 86088138,
    "type": "Normal Monster",
    "desc": "Frightening in appearance, this creature uses its large eyes and ears to keep track of any movement.",
    "atk": 1550,
    "def": 1650,
    "level": 5,
    "race": "Fairy",
    "attribute": "LIGHT"
  },
  {
    "name": "Ooguchi",
    "art": "rbxgameasset://Images/card-58861941",
    "id": 58861941,
    "type": "Effect Monster",
    "desc": "This monster may attack your opponent's Life Points directly.",
    "atk": 300,
    "def": 250,
    "level": 1,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Pale Beast",
    "art": "rbxgameasset://Images/card-21263083",
    "id": 21263083,
    "type": "Normal Monster",
    "desc": "With skin tinged a bluish-white, this strange creature is a fearsome sight to behold.",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Paralyzing Potion",
    "art": "rbxgameasset://Images/card-50152549",
    "id": 50152549,
    "type": "Spell Card",
    "desc": "A non Machine-Type monster equipped with this card cannot attack.",
    "race": "Equip"
  },
  {
    "name": "Petit Moth",
    "art": "rbxgameasset://Images/card-58192742",
    "id": 58192742,
    "type": "Normal Monster",
    "desc": "This small but deadly creature is better off avoided.",
    "atk": 300,
    "def": 200,
    "level": 1,
    "race": "Insect",
    "attribute": "EARTH"
  },
  {
    "name": "Prevent Rat",
    "art": "rbxgameasset://Images/card-549481",
    "id": 549481,
    "type": "Normal Monster",
    "desc": "This creature is shielded with a tough hide of hair and is excellent at defending itself.",
    "atk": 500,
    "def": 2000,
    "level": 4,
    "race": "Beast",
    "attribute": "EARTH"
  },
  {
    "name": "Princess of Tsurugi",
    "art": "rbxgameasset://Images/card-51371017",
    "id": 51371017,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Inflict 500 damage to your opponent for each Spell and Trap Card on your opponent's side of the field.",
    "atk": 900,
    "def": 700,
    "level": 3,
    "race": "Warrior",
    "attribute": "WIND"
  },
  {
    "name": "Protector of the Throne",
    "art": "rbxgameasset://Images/card-10071456",
    "id": 10071456,
    "type": "Normal Monster",
    "desc": "While the king is away, this queen protects his throne with a mighty defense.",
    "atk": 800,
    "def": 1500,
    "level": 4,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Pumpking the King of Ghosts",
    "art": "rbxgameasset://Images/card-29155212",
    "id": 29155212,
    "type": "Effect Monster",
    "desc": "If \"Castle of Dark Illusions\" is face-up on the field, increase the ATK and DEF of this card by 100 points. As long as this \"Castle of Dark Illusions\" remains face-up on the field, the ATK and DEF of this card continues to increase by 100 points during each of your Standby Phases. This effect continues until your 4th turn after the card is activated.",
    "atk": 1800,
    "def": 2000,
    "level": 6,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "Punished Eagle",
    "art": "rbxgameasset://Images/card-74703140",
    "id": 74703140,
    "type": "Fusion Monster",
    "desc": "\"Blue-Winged Crown\" + \"Niwatori\"",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "race": "Winged Beast",
    "attribute": "WIND"
  },
  {
    "name": "Queen's Double",
    "art": "rbxgameasset://Images/card-5901497",
    "id": 5901497,
    "type": "Effect Monster",
    "desc": "This monster may attack your opponent's Life Points directly.",
    "atk": 350,
    "def": 300,
    "level": 1,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Rabid Horseman",
    "art": "rbxgameasset://Images/card-94905343",
    "id": 94905343,
    "type": "Fusion Monster",
    "desc": "\"Battle Ox\" + \"Mystic Horseman\"",
    "atk": 2000,
    "def": 1700,
    "level": 6,
    "race": "Beast-Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Rainbow Flower",
    "art": "rbxgameasset://Images/card-21347810",
    "id": 21347810,
    "type": "Effect Monster",
    "desc": "This monster may attack your opponent's Life Points directly.",
    "atk": 400,
    "def": 500,
    "level": 2,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Ring of Magnetism",
    "art": "rbxgameasset://Images/card-20436034",
    "id": 20436034,
    "type": "Spell Card",
    "desc": "You can only equip this card to a monster on your side of the field. Decrease the ATK and DEF of a monster equipped with this card by 500 points. In addition, all the monsters on your opponent's side of the field can only attack the monster equipped with this card, if they attack.",
    "race": "Equip"
  },
  {
    "name": "Roaring Ocean Snake",
    "art": "rbxgameasset://Images/card-19066538",
    "id": 19066538,
    "type": "Fusion Monster",
    "desc": "\"Mystic Lamp\" + \"Hyosube\"",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Robbin' Goblin",
    "art": "rbxgameasset://Images/card-88279736",
    "id": 88279736,
    "type": "Trap Card",
    "desc": "Each time a monster you control inflicts Battle Damage to your opponent, your opponent discards 1 random card.",
    "race": "Continuous"
  },
  {
    "name": "Rock Ogre Grotto #1",
    "art": "rbxgameasset://Images/card-68846917",
    "id": 68846917,
    "type": "Normal Monster",
    "desc": "Protected by a solid body of rock, this monster throws a bone-shattering punch.",
    "atk": 800,
    "def": 1200,
    "level": 3,
    "race": "Rock",
    "attribute": "EARTH"
  },
  {
    "name": "Ryu-Kishin Powered",
    "art": "rbxgameasset://Images/card-24611934",
    "id": 24611934,
    "type": "Normal Monster",
    "desc": "A gargoyle enhanced by the powers of darkness. Very sharp talons make it a worthy opponent.",
    "atk": 1600,
    "def": 1200,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Saggi the Dark Clown",
    "art": "rbxgameasset://Images/card-66602787",
    "id": 66602787,
    "type": "Normal Monster",
    "desc": "This clown appears from nowhere and executes very strange moves to avoid enemy attacks.",
    "atk": 600,
    "def": 1500,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Sanga of the Thunder",
    "art": "rbxgameasset://Images/card-25955164",
    "id": 25955164,
    "type": "Effect Monster",
    "desc": "During damage calculation in your opponent's turn, if this card is being attacked: You can target the attacking monster; make that target's ATK 0 during damage calculation only (this is a Quick Effect). This effect can only be used once while this card is face-up on the field.",
    "atk": 2600,
    "def": 2200,
    "level": 7,
    "race": "Thunder",
    "attribute": "LIGHT"
  },
  {
    "name": "Sangan",
    "art": "rbxgameasset://Images/card-26202165",
    "id": 26202165,
    "type": "Effect Monster",
    "desc": "If this card is sent from the field to the GY: Add 1 monster with 1500 or less ATK from your Deck to your hand, but you cannot activate cards, or the effects of cards, with that name for the rest of this turn. You can only use this effect of \"Sangan\" once per turn.",
    "atk": 1000,
    "def": 600,
    "level": 3,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Seven Tools of the Bandit",
    "art": "rbxgameasset://Images/card-3819470",
    "id": 3819470,
    "type": "Trap Card",
    "desc": "When a Trap Card is activated: Pay 1000 LP; negate the activation, and if you do, destroy it.",
    "race": "Counter"
  },
  {
    "name": "Shadow Ghoul",
    "art": "rbxgameasset://Images/card-30778711",
    "id": 30778711,
    "type": "Effect Monster",
    "desc": "This card gains 100 ATK for each monster in your Graveyard.",
    "atk": 1600,
    "def": 1300,
    "level": 5,
    "race": "Zombie",
    "attribute": "DARK"
  },
  {
    "name": "Share the Pain",
    "art": "rbxgameasset://Images/card-56830749",
    "id": 56830749,
    "type": "Spell Card",
    "desc": "Tribute 1 monster; make your opponent Tribute 1 monster (for no effect).",
    "race": "Normal"
  },
  {
    "name": "Shield & Sword",
    "art": "rbxgameasset://Images/card-52097679",
    "id": 52097679,
    "type": "Spell Card",
    "desc": "Switch the original ATK and DEF of all face-up monsters currently on the field, until the end of this turn.",
    "race": "Normal"
  },
  {
    "name": "Skull Knight",
    "art": "rbxgameasset://Images/card-2504891",
    "id": 2504891,
    "type": "Fusion Monster",
    "desc": "\"Tainted Wisdom\" + \"Ancient Brain\"",
    "atk": 2650,
    "def": 2250,
    "level": 7,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Solemn Judgment",
    "art": "rbxgameasset://Images/card-41420027",
    "id": 41420027,
    "type": "Trap Card",
    "desc": "When a monster(s) would be Summoned, OR a Spell/Trap Card is activated: Pay half your LP; negate the Summon or activation, and if you do, destroy that card.",
    "race": "Counter"
  },
  {
    "name": "Soul Release",
    "art": "rbxgameasset://Images/card-5758500",
    "id": 5758500,
    "type": "Spell Card",
    "desc": "Target up to 5 cards in any GY(s); banish them.",
    "race": "Normal"
  },
  {
    "name": "Star Boy",
    "art": "rbxgameasset://Images/card-8201910",
    "id": 8201910,
    "type": "Effect Monster",
    "desc": "As long as this card remains face-up on the field, increase the ATK of all WATER monsters by 500 points and decrease the ATK of all FIRE monsters by 400 points.",
    "atk": 550,
    "def": 500,
    "level": 2,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Steel Scorpion",
    "art": "rbxgameasset://Images/card-13599884",
    "id": 13599884,
    "type": "Effect Monster",
    "desc": "A non Machine-Type Monster attacking \"Steel Scorpion\" will be destroyed at the End Phase of your opponent's 2nd turn after the attack.",
    "atk": 250,
    "def": 300,
    "level": 1,
    "race": "Machine",
    "attribute": "EARTH"
  },
  {
    "name": "Stim-Pack",
    "art": "rbxgameasset://Images/card-83225447",
    "id": 83225447,
    "type": "Spell Card",
    "desc": "The equipped monster gains 700 ATK. During each of your Standby Phases, the equipped monster loses 200 ATK.",
    "race": "Equip"
  },
  {
    "name": "Suijin",
    "art": "rbxgameasset://Images/card-98434877",
    "id": 98434877,
    "type": "Effect Monster",
    "desc": "During damage calculation in your opponent's turn, if this card is being attacked: You can target the attacking monster; make that target's ATK 0 during damage calculation only (this is a Quick Effect). This effect can only be used once while this card is face-up on the field.",
    "atk": 2500,
    "def": 2400,
    "level": 7,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "Summoned Skull",
    "art": "rbxgameasset://Images/card-70781052",
    "id": 70781052,
    "type": "Normal Monster",
    "desc": "A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, this monster boasts considerable force.\n\n(This card is always treated as an \"Archfiend\" card.)",
    "atk": 2500,
    "def": 1200,
    "level": 6,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "Swamp Battleguard",
    "art": "rbxgameasset://Images/card-40453765",
    "id": 40453765,
    "type": "Effect Monster",
    "desc": "This card gains 500 ATK for each \"Lava Battleguard\" you control.",
    "atk": 1800,
    "def": 1500,
    "level": 5,
    "race": "Warrior",
    "attribute": "EARTH"
  },
  {
    "name": "Sword of Deep-Seated",
    "art": "rbxgameasset://Images/card-98495314",
    "id": 98495314,
    "type": "Spell Card",
    "desc": "The equipped monster gains 500 ATK/DEF. If this card is sent to your GY: Place it on top of your Deck.",
    "race": "Equip"
  },
  {
    "name": "Tainted Wisdom",
    "art": "rbxgameasset://Images/card-28725004",
    "id": 28725004,
    "type": "Effect Monster",
    "desc": "If this Attack Position card is changed to face-up Defense Position: Shuffle your Deck.",
    "atk": 1250,
    "def": 800,
    "level": 3,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "The Bistro Butcher",
    "art": "rbxgameasset://Images/card-71107816",
    "id": 71107816,
    "type": "Effect Monster",
    "desc": "When this card inflicts Battle Damage to your opponent, your opponent draws 2 cards.",
    "atk": 1800,
    "def": 1000,
    "level": 4,
    "race": "Fiend",
    "attribute": "DARK"
  },
  {
    "name": "The Cheerful Coffin",
    "art": "rbxgameasset://Images/card-41142615",
    "id": 41142615,
    "type": "Spell Card",
    "desc": "Discard up to 3 Monster Cards from your hand to the Graveyard.",
    "race": "Normal"
  },
  {
    "name": "The Immortal of Thunder",
    "art": "rbxgameasset://Images/card-84926738",
    "id": 84926738,
    "type": "Flip Effect Monster",
    "desc": "FLIP: Increase your Life Points by 3000 points. When this card is sent from the field to the Graveyard, you lose 5000 Life Points.",
    "atk": 1500,
    "def": 1300,
    "level": 4,
    "race": "Thunder",
    "attribute": "LIGHT"
  },
  {
    "name": "The Little Swordsman of Aile",
    "art": "rbxgameasset://Images/card-25109950",
    "id": 25109950,
    "type": "Effect Monster",
    "desc": "Offer 1 monster on your side of the field as a Tribute to increase this monster's ATK by 700 points until the end of the turn.",
    "atk": 800,
    "def": 1300,
    "level": 3,
    "race": "Warrior",
    "attribute": "WATER"
  },
  {
    "name": "The Unhappy Maiden",
    "art": "rbxgameasset://Images/card-51275027",
    "id": 51275027,
    "type": "Effect Monster",
    "desc": "When this card is sent to the Graveyard as a result of battle, the Battle Phase for that turn ends immediately.",
    "atk": 0,
    "def": 100,
    "level": 1,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Thousand Dragon",
    "art": "rbxgameasset://Images/card-41462083",
    "id": 41462083,
    "type": "Fusion Monster",
    "desc": "\"Time Wizard\" + \"Baby Dragon\"",
    "atk": 2400,
    "def": 2000,
    "level": 7,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Thunder Dragon",
    "art": "rbxgameasset://Images/card-31786629",
    "id": 31786629,
    "type": "Effect Monster",
    "desc": "You can discard this card; add up to 2 \"Thunder Dragon\" from your Deck to your hand.",
    "atk": 1600,
    "def": 1500,
    "level": 5,
    "race": "Thunder",
    "attribute": "LIGHT"
  },
  {
    "name": "Time Wizard",
    "art": "rbxgameasset://Images/card-71625222",
    "id": 71625222,
    "type": "Effect Monster",
    "desc": "Once per turn: You can toss a coin and call it. If you call it right, destroy all monsters your opponent controls. If you call it wrong, destroy as many monsters you control as possible, and if you do, take damage equal to half the total ATK those destroyed monsters had while face-up on the field.",
    "atk": 500,
    "def": 400,
    "level": 2,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Tongyo",
    "art": "rbxgameasset://Images/card-69572024",
    "id": 69572024,
    "type": "Normal Monster",
    "desc": "This monster captures other fish with its long tongue and sucks the energy out of them.",
    "atk": 1350,
    "def": 800,
    "level": 4,
    "race": "Fish",
    "attribute": "WATER"
  },
  {
    "name": "Tremendous Fire",
    "art": "rbxgameasset://Images/card-46918794",
    "id": 46918794,
    "type": "Spell Card",
    "desc": "Inflict 1000 points of damage to your opponent's Life Points and 500 points of damage to your Life Points.",
    "race": "Normal"
  },
  {
    "name": "Trent",
    "art": "rbxgameasset://Images/card-78780140",
    "id": 78780140,
    "type": "Normal Monster",
    "desc": "A guardian of the woods, this massive tree is believed to be immortal.",
    "atk": 1500,
    "def": 1800,
    "level": 5,
    "race": "Plant",
    "attribute": "EARTH"
  },
  {
    "name": "Tribute to the Doomed",
    "art": "rbxgameasset://Images/card-79759861",
    "id": 79759861,
    "type": "Spell Card",
    "desc": "Discard 1 card, then target 1 monster on the field; destroy it.",
    "race": "Normal"
  },
  {
    "name": "Twin-Headed Thunder Dragon",
    "art": "rbxgameasset://Images/card-54752875",
    "id": 54752875,
    "type": "Fusion Monster",
    "desc": "\"Thunder Dragon\" + \"Thunder Dragon\"",
    "atk": 2800,
    "def": 2100,
    "level": 7,
    "race": "Thunder",
    "attribute": "LIGHT"
  },
  {
    "name": "Water Omotics",
    "art": "rbxgameasset://Images/card-2483611",
    "id": 2483611,
    "type": "Normal Monster",
    "desc": "Transforms the water overflowing from a jar into attacking dragons.",
    "atk": 1400,
    "def": 1200,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  },
  {
    "name": "White Magical Hat",
    "art": "rbxgameasset://Images/card-15150365",
    "id": 15150365,
    "type": "Effect Monster",
    "desc": "When this card inflicts Battle Damage to your opponent's Life Points, your opponent discards 1 card randomly from his/her hand.",
    "atk": 1000,
    "def": 700,
    "level": 3,
    "race": "Spellcaster",
    "attribute": "LIGHT"
  },
  {
    "name": "Winged Dragon, Guardian of the Fortress #1",
    "art": "rbxgameasset://Images/card-87796900",
    "id": 87796900,
    "type": "Normal Monster",
    "desc": "A dragon commonly found guarding mountain fortresses. Its signature attack is a sweeping dive from out of the blue.",
    "atk": 1400,
    "def": 1200,
    "level": 4,
    "race": "Dragon",
    "attribute": "WIND"
  },
  {
    "name": "Witch of the Black Forest",
    "art": "rbxgameasset://Images/card-78010363",
    "id": 78010363,
    "type": "Effect Monster",
    "desc": "If this card is sent from the field to the GY: Add 1 monster with 1500 or less DEF from your Deck to your hand, but you cannot activate cards, or the effects of cards, with that name for the rest of this turn. You can only use this effect of \"Witch of the Black Forest\" once per turn.",
    "atk": 1100,
    "def": 1200,
    "level": 4,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Witch's Apprentice",
    "art": "rbxgameasset://Images/card-80741828",
    "id": 80741828,
    "type": "Effect Monster",
    "desc": "As long as this card remains face-up on the field, increase the ATK of all DARK monsters by 500 points and decrease the ATK of all LIGHT monsters by 400 points.",
    "atk": 550,
    "def": 500,
    "level": 2,
    "race": "Spellcaster",
    "attribute": "DARK"
  },
  {
    "name": "Yado Karu",
    "art": "rbxgameasset://Images/card-29380133",
    "id": 29380133,
    "type": "Effect Monster",
    "desc": "When this card is changed from Attack Position to Defense Position, you can place any number of cards from your hand at the bottom of your Deck in any order you desire.",
    "atk": 900,
    "def": 1700,
    "level": 4,
    "race": "Aqua",
    "attribute": "WATER"
  }
];
